---
deployment:
  tasks:
    - export APPPATH=$HOME/318produtora
    - export PUBPATH=$HOME/public_html
    - /bin/mkdir -p $APPPATH
    - /bin/rsync -av --delete --exclude='.git' --exclude='public' ./ $APPPATH/
    - /bin/rsync -av --delete ./public/ $PUBPATH/
    - /usr/local/bin/php $HOME/composer.phar install --no-dev --optimize-autoloader --no-interaction --working-dir=$APPPATH
    - /usr/local/bin/php $APPPATH/artisan migrate --force
    - /usr/local/bin/php $APPPATH/artisan config:cache
    - /usr/local/bin/php $APPPATH/artisan route:cache
    - /usr/local/bin/php $APPPATH/artisan view:cache
    - /bin/ln -sfn $APPPATH/storage/app/public $PUBPATH/storage
    - /bin/chmod -R 775 $APPPATH/storage
    - /bin/chmod -R 775 $APPPATH/bootstrap/cache
